name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # Roda todo dia à meia-noite
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Generate Snake (SVG para o ano todo)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: VictorFlamengo
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          # esse parâmetro faz pegar o ano inteiro
          args: --year

      - name: Deploy Snake to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
